### Send POST request with json body
POST https://agile-cliffs-49290.herokuapp.com/api/mail/send/
Content-Type: application/json

{
  "username": "Lallulal",
  "send_to": "nehamahto132@gmail.com"
}
###

### Send POST request with json body
POST http://localhost:8000/api/mail/send/
Content-Type: application/json

{
  "username": "Lallulal",
  "send_to": "nehamahto132@gmail.com"
}
###

###
GET http://localhost:8000/api/server/
###

###
POST http://localhost:8000/api/server/detect/
Content-Type: application/json

{
    "text": "You have purchased ABC for Rs 1000. The remaining balance in your account is Rs 15,345.00"
}
###

###
GET https://agile-cliffs-49290.herokuapp.com/api/server/
###

###
POST https://agile-cliffs-49290.herokuapp.com/api/server/detect/
Content-Type: application/json

{
  "text": "You have purchased ABC for Rs 1000. The remaining balance in your account is Rs 15,345.00"
}
###

###
POST https://agile-cliffs-49290.herokuapp.com/api/server/detect/
Content-Type: application/json

{
  "text": "You have purchased ABC for Rs 1000. The remaining balance in your account is Rs 15,345.00",
  "regex": "Rs\\ ?[+-]?[0-9]{1,3}(?:,?[0-9])*(?:\\.[0-9]{1,2})?"
}
###

###
POST http://localhost:8000/api/regex/create/
Content-Type: application/json

{
  "label": "You have purchased ABC for Rs 1000. The remaining balance in your account is Rs 15,345.00",
  "regex": "\\w+"
}
###

###
GET http://localhost:8000/api/regex/4/delete/
###

POST http://localhost:8000/api/regex/22/edit/
Content-Type: application/json

{
  "label": "amount",
  "regex": "\\w"
}
###